# Source: postgresql/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simple-bank-postgresql
spec:
  replicas: 2
  template:
    metadata:
      name: simple-bank-postgresql
    spec:
      containers:
        - name: postgresql
          env:
            # Authentication
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-simple-bank-secrets
                  key: DB_PASSWORD