apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-bank-service-postgres
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # namespace where final app pods are deployment
  project: simple-bank-service # project name of argo's app project (../app-project.yaml)
  source:
    helm:
      parameters:
      - name: global.postgresql.auth.username
        value: asdasdsadasdasdasdsadsadasdasdsaasdsad
      valueFiles:
      - values.yaml
    path: bitnami/postgresql
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
